### Задание 1

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
import numpy as np

z = np.arange(0,int(input()))[::-1]
z


10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [23]:
n=int(input())
x = np.diag(np.arange(n)[::-1], k=0)
print(x)
total = 0
for i in range(n):
    total+=x[i][i]
print('Сумма по диагонали =', total)

11
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]
Сумма по диагонали = 55


### Задание 3

Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [8]:
import pandas as pd
data = pd.read_csv('ratings.csv')
data2 = data [ (data['rating'] == 5.0)]
data3 = data2.groupby('movieId').count().sort_values('userId', ascending = False).head(1)
data3.iloc[:,0:0] 


Empty DataFrame
Columns: []
Index: [318]

### Задание 4

По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity

In [17]:
data = pd.read_csv('power.csv')

filter1 = data[ (data['country']=='Latvia') | (data['country']=='Lithuania') | (data['country'] == 'Estonia') ]
filter2 = filter1[ (filter1['category'] ==4 ) |(filter1['category'] ==12 )| (filter1['category'] ==21 ) ]
filter3 = filter2[ (filter2['year']>2004)& (filter2['year'] < 2011)  ]
filter4 = (filter3[(filter3['quantity'] > 0)])['quantity'].sum()
print('Суммарное потребление стран Прибалтики после применения всех условий = ', filter4, 'единиц')


Суммарное потребление стран Прибалтики после применения всех условий =  240580.0 единиц


### Задание 5

Решите систему уравнений:
- 4x + 2y + z = 4
- x + 3y = 12
- 5y + 4z = -3

In [26]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])